### ISSUE TITLE
No live update in docker deployment

### ISSUE THREAD

**Issue by Olivier-Heliot** [majeinfo/nagios2grafana#1]
Hi! Jérôme! 
Thanks for your nice work! One remark: in my Docker deployment, there was no live update of Nagios data, that is a little annoying for monitoring tool. 
My correction: I share the directory of status.dat file rather than the file it self. To do so I need to change the entrypoint (it would have be better not to share status.dat file (data) and program /app directory)
Here is my docker-compose file:

```
version: "2.2"
services:
  nagios2grafana:
    image: majetraining/nagios2grafana
    container_name: nagios2grafana
    hostname: nagios2grafana
    volumes:
      - /usr/local/nagios/var/:/var/nagios/
    entrypoint: gunicorn -b 0.0.0.0:5000 nagios2grafana:app(nagios_status_file=\"/var/nagios/status.dat\")
    ports:
      - 5000:5000
    restart: always
```
Best regards,
Olivier
